spring:
  application:
    name: gerenciador-estoque

  data:
    mongodb:
      uri: mongodb://localhost:27017/estoquedb

  logging:
    level:
      org.springframework.security: DEBUG
      oliveiradev.inventario.infra.security: DEBUG
      oliveiradev.inventario.interfaces.controller: DEBUG

app:
  jwt:
    # Este segredo é usado pelo JwtTokenProvider
    secret: k1ZXzu4t/WpgHtynifYBjpPGFAUUrzs9185YgPnY5WgCf1ZhoOMCbkwmjjkxmWcm2+bFt50bT+HJtk8fWfSPHQ==
    expiration-ms: 3600000 # 1 hora