spring:
  application:
    name: gerenciador-estoque

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}

  # logging
  logging:
    level:
      org.springframework.security: DEBUG
      oliveiradev.inventario.infra.security: DEBUG
      oliveiradev.inventario.interfaces.controller: DEBUG

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-ms: 3600000 # 1 hora
